# Generated by Django 3.0.3 on 2020-02-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
